# Generated by Django 3.1.5 on 2021-03-19 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organizationinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='driver_assign_sms',
            field=models.CharField(default='A rider has been assigned to your order #{{order_ref}}. {{rider_name}} will contact you on  {{rider_phone}}', max_length=150),
        ),
        migrations.AddField(
            model_name='organization',
            name='driver_complete_sms',
            field=models.CharField(default='Thank you. How was your experience. Leave us a rating.', max_length=150),
        ),
        migrations.AddField(
            model_name='organization',
            name='driver_reassign_sms',
            field=models.CharField(default='A different rider has been assigned to your order #{{order_ref}}. {{rider_name}} will contact you on  {{rider_phone}}', max_length=150),
        ),
        migrations.AddField(
            model_name='organization',
            name='driver_start_sms',
            field=models.CharField(default='Your rider is on the way. {{rider_name}} will contact you on {{rider_phone}}', max_length=150),
        ),
        migrations.AddField(
            model_name='organization',
            name='order_received_sms',
            field=models.CharField(default='Hi {{first_name}}, your order #{{order_ref}} has be been received and will be dispatched shortly.', max_length=150),
        ),
        migrations.AddField(
            model_name='organization',
            name='send_driver_assign_sms',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='send_driver_complete_sms',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='send_driver_reassign_sms',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='send_driver_start_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='send_order_received_sms',
            field=models.BooleanField(default=True),
        ),
    ]
