# Generated by Django 3.1.5 on 2021-05-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20210319_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='country',
            field=models.CharField(default='Kenya', max_length=255),
            preserve_default=False,
        ),
    ]
