# Generated by Django 3.1.5 on 2021-12-08 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_organisationsmsprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMpesaDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_short_code', models.CharField(max_length=20)),
                ('consumer_key', models.CharField(max_length=300)),
                ('consumer_secret', models.CharField(max_length=300)),
                ('pass_key', models.CharField(max_length=300)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
        ),
        migrations.DeleteModel(
            name='OrganisationSmsProvider',
        ),
    ]
