# Generated by Django 3.1.5 on 2022-01-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_organization_googlemap_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='timezone',
            field=models.CharField(default='Africa/Nairobi', max_length=75),
            preserve_default=False,
        ),
    ]
