# Generated by Django 3.1.5 on 2022-02-16 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_organization_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsmsprovider',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
    ]
