# Generated by Django 3.1.5 on 2022-02-18 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0016_auto_20220217_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='sync_callback_url',
            field=models.URLField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organizationsmsprovider',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
    ]
