# Generated by Django 3.1.5 on 2021-03-04 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salt', models.CharField(max_length=255)),
                ('iteration_count', models.IntegerField()),
                ('stored_key', models.CharField(max_length=255)),
                ('server_key', models.CharField(max_length=255)),
                ('deleted', models.BooleanField(default=False)),
                ('uid', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=75, null=True)),
                ('first_name', models.CharField(max_length=75, null=True)),
                ('national_number', models.BigIntegerField()),
                ('phone_number', models.BigIntegerField(unique=True)),
                ('country_prefix', models.PositiveSmallIntegerField()),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.URLField(max_length=2048, null=True)),
                ('thumbnail', models.URLField(max_length=2048, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_added_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_modified_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
        ),
    ]
