# Generated by Django 3.1.5 on 2021-03-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='driver',
            unique_together={('phone_number', 'organization')},
        ),
    ]
