# Generated by Django 3.1.5 on 2021-03-11 23:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_auto_20210305_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverAuth',
            fields=[
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('password_hash', models.CharField(max_length=2048)),
                ('token', models.CharField(max_length=255, null=True)),
                ('avatar', models.URLField(max_length=2048, null=True)),
                ('thumbnail', models.URLField(max_length=2048, null=True)),
                ('phone_number', models.BigIntegerField(primary_key=True, serialize=False)),
                ('verification_code', models.PositiveIntegerField(null=True)),
                ('verification_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('verification_tries', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='driver',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='country_prefix',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='iteration_count',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='national_number',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='salt',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='server_key',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='stored_key',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='uid',
        ),
    ]
