# Generated by Django 3.1.5 on 2021-03-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_auto_20210311_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverauth',
            name='first_name',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='driverauth',
            name='is_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driverauth',
            name='last_name',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
