# Generated by Django 3.1.5 on 2021-03-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_auto_20210313_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='reg_no',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
