# Generated by Django 3.1.5 on 2021-03-24 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0005_auto_20210321_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='reg_no',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
