# Generated by Django 3.1.5 on 2021-03-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0006_auto_20210324_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverauth',
            name='lat',
            field=models.DecimalField(decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='driverauth',
            name='lng',
            field=models.DecimalField(decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='driverauth',
            name='location_update_time',
            field=models.DateTimeField(null=True),
        ),
    ]
