# Generated by Django 3.1.5 on 2021-04-30 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0007_auto_20210325_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverAuthFCM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=2048)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_fail_time', models.DateTimeField(null=True)),
                ('failed_tries', models.PositiveSmallIntegerField(default=0)),
                ('driver_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.driverauth')),
            ],
            options={
                'unique_together': {('driver_auth', 'token')},
            },
        ),
    ]
