# Generated by Django 3.1.5 on 2021-05-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0008_driverauthfcm'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverauthfcm',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
