# Generated by Django 3.1.5 on 2021-05-07 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0009_driverauthfcm_is_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverauth',
            name='token',
        ),
        migrations.CreateModel(
            name='DriverAuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(max_length=2048, unique=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('driver_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.driverauth')),
            ],
            options={
                'unique_together': {('driver_auth', 'token')},
            },
        ),
    ]
