# Generated by Django 3.1.5 on 2021-05-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0010_auto_20210507_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverauth',
            name='code_send_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
