# Generated by Django 3.1.5 on 2022-02-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0011_driverauth_code_send_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='prev_id',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='prev_id_external',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
    ]
