# Generated by Django 3.1.5 on 2022-02-25 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0016_auto_20220225_1659'),
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='route',
            name='distance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='route',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='route',
            name='end_lat',
            field=models.DecimalField(decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='end_lng',
            field=models.DecimalField(decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='geometry',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='order_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='route',
            name='start_lat',
            field=models.DecimalField(decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='start_lng',
            field=models.DecimalField(decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_added_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='route',
            name='details',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RouteItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eta', models.DateTimeField(null=True)),
                ('distance', models.PositiveIntegerField(default=0)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('service_time', models.PositiveIntegerField(default=0)),
                ('waiting_time', models.PositiveIntegerField(default=0)),
                ('_type', models.PositiveSmallIntegerField(choices=[(1, 'Pickup'), (2, 'Dropoff')])),
                ('lat', models.DecimalField(decimal_places=9, max_digits=12, null=True)),
                ('lng', models.DecimalField(decimal_places=9, max_digits=12, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, ' Not Started'), (2, 'Started'), (3, 'Completed'), (4, 'Failed')], default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitem_order', to='order.order')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitem_route', to='route.route')),
            ],
        ),
    ]
