# Generated by Django 3.1.5 on 2021-07-20 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0005_organization_callback_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('reg_no', models.CharField(max_length=255, null=True)),
                ('width', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('length', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('service_start', models.PositiveSmallIntegerField(choices=[(0, '12:00AM'), (1, '01:00AM'), (2, '02:00AM'), (3, '03:00AM'), (4, '04:00AM'), (5, '05:00AM'), (6, '06:00AM'), (7, '07:00AM'), (8, '08:00AM'), (9, '09:00AM'), (10, '10:00AM'), (11, '11:00AM'), (12, '12:00PM'), (13, '01:00PM'), (14, '02:00PM'), (15, '03:00PM'), (16, '04:00PM'), (17, '05:00PM'), (18, '06:00PM'), (19, '07:00PM'), (20, '08:00PM'), (21, '09:00PM'), (22, '10:00PM'), (23, '11:00PM')], default=8)),
                ('service_end', models.PositiveSmallIntegerField(choices=[(0, '12:00AM'), (1, '01:00AM'), (2, '02:00AM'), (3, '03:00AM'), (4, '04:00AM'), (5, '05:00AM'), (6, '06:00AM'), (7, '07:00AM'), (8, '08:00AM'), (9, '09:00AM'), (10, '10:00AM'), (11, '11:00AM'), (12, '12:00PM'), (13, '01:00PM'), (14, '02:00PM'), (15, '03:00PM'), (16, '04:00PM'), (17, '05:00PM'), (18, '06:00PM'), (19, '07:00PM'), (20, '08:00PM'), (21, '09:00PM'), (22, '10:00PM'), (23, '11:00PM')], default=17)),
                ('address', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=16, max_digits=22)),
                ('lng', models.DecimalField(decimal_places=16, max_digits=22)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_added_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_modified_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
        ),
    ]
