# Generated by Django 3.1.5 on 2021-03-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210322_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_notes',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Prepaid'), (2, 'Postpaid - Cash'), (2, 'Postpaid - Mobile money'), (4, 'Credit')], default=1),
        ),
    ]
