# Generated by Django 3.1.5 on 2021-03-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210325_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Prepaid'), (2, 'Postpaid - Cash'), (3, 'Postpaid - Mobile money'), (4, 'Credit')], default=1),
        ),
    ]
