# Generated by Django 3.1.5 on 2021-12-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_organization_allow_driver_to_self_assign_orders'),
        ('order', '0008_auto_20211209_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('ref', 'organization'), ('sid', 'organization')},
        ),
    ]
