# Generated by Django 3.1.5 on 2021-12-22 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_organization_googlemap_api_key'),
        ('order', '0009_auto_20211216_1254'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('ref', 'organization')},
        ),
    ]
