# Generated by Django 3.1.5 on 2022-01-03 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20211222_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='CheckoutRequestID',
        ),
        migrations.RemoveField(
            model_name='order',
            name='MerchantRequestID',
        ),
        migrations.RemoveField(
            model_name='order',
            name='MpesaReceiptNumber',
        ),
        migrations.RemoveField(
            model_name='order',
            name='PhoneNumber',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ResultCode',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ResultDesc',
        ),
        migrations.RemoveField(
            model_name='order',
            name='TransactionDate',
        ),
        migrations.CreateModel(
            name='MpesaPayments',
            fields=[
                ('MpesaReceiptNumber', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('MerchantRequestID', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('CheckoutRequestID', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('ResultCode', models.IntegerField(blank=True, default=0, null=True)),
                ('ResultDesc', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('Amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('PhoneNumber', models.CharField(blank=True, default='', max_length=13, null=True)),
                ('TransactionDate', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
