# Generated by Django 3.1.5 on 2022-01-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20220103_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='state',
            field=models.PositiveIntegerField(choices=[(2, 'Not collected'), (1, 'Collected for delivery'), (3, 'Damaged in transit'), (4, 'Rejected by recipeint'), (7, 'Delivered'), (5, 'Returned to warehouse'), (6, 'Recieved at warehouse')], default=2),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
