# Generated by Django 3.1.5 on 2022-02-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20220103_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFailure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=1024)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='prev_id',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='prev_id_external',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='review',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.PositiveIntegerField(choices=[(1, 'Submitted'), (2, 'Driver Unassigned'), (3, 'Driver Assigned'), (4, 'in progress'), (5, 'Arrival at client'), (6, 'Failed'), (7, 'Delivered'), (8, 'failed awaiting warehouse'), (9, 'Delivered at warehouse'), (10, 'Returned from warehouse'), (11, 'Recieved from warehouse'), (12, 'Cancelled'), (13, 'Rescheduled')], default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='failures',
            field=models.ManyToManyField(to='order.OrderFailure'),
        ),
    ]
