# Generated by Django 3.1.5 on 2022-02-17 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_auto_20220216_0942'),
        ('driver', '0012_auto_20220215_2354'),
        ('order', '0013_auto_20220215_2354'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='order',
            index_together={('datetime_ordered', 'state', 'organization'), ('rider', 'datetime_ordered', 'state', 'organization'), ('rating', 'datetime_ordered', 'organization')},
        ),
    ]
